baseURL: https://gaia-pipeline.io/
languageCode: en-us
title: Gaia - Build powerful pipelines in any programming language.
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Gaia
    # Hero subtitle (optional)
    subtitle: Build powerful pipelines in any programming language.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://docs.gaia-pipeline.io/getting-started/"
    # Footer logos (from /images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: "#features"
  - title: Download
    url: https://github.com/gaia-pipeline/gaia/releases
    target: _blank
  - title: Docs
    url: https://docs.gaia-pipeline.io
    target: _blank
  - title: Tutorials
    url: https://docs.gaia-pipeline.io/tutorials/
    target: _blank
  - title: Get started
    url: https://docs.gaia-pipeline.io/getting-started/
    button: true
  section1:
    title: What is Gaia?
    subtitle: Gaia enables DevOps and makes developers happy. 
    tiles:
    - title: Multilingual 
      icon: code.png
      text: Write pipelines in Go, Java, Python and C++.
      url: https://docs.gaia-pipeline.io/develop-pipelines/
      buttonText: Learn more
    - title: Super fast and lightweight
      icon: speed.png
      text: Based on Go and gRPC, Gaia is super fast and lightweight.
      url: https://github.com/gaia-pipeline/gaia#how-does-it-work
      buttonText: Learn more
    - title: Developer friendly
      icon: automation.png
      text: Do automation in a way developers know and love.
      url: https://docs.gaia-pipeline.io/tutorials/kube-vault-deploy/
      buttonText: Learn more
  section2:
    title: Features
    subtitle: Gaia is efficient, fast, lightweight, and developer friendly.
    features:
    - title: Programming language independent
      text: Gaia is programming language independent and basically any programming language can be used to write pipelines. At this point of time we officially support Go, Java, Python and C++. Your favorite language is not supported? Open a new issue and request it!
      icon: code.png
    - title: Testing desired
      text: Test your pipelines and write unit tests like you do for your applications. No excuses anymore to do testing right for your automation pipelines.   
      icon: bug.png
    - title: Simple and efficient
      text: Gaia comes with the automatic build feature for pipelines. Simply push your code to a git repository. Gaia automatically clones your code repository, compiles your code to a binary and executes it on-demand.
      icon: genius.png
    - title: Open-source
      text: Gaia is open-source and will always be! Feel free to have a look at the source code, discuss new features and help us to improve it!
      icon: github.png
  section4:
    title: Examples
    subtitle: Write your own pipeline within seconds!
  footer:
    logo: gaia-logo-text.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/gaia-pipeline/gaia
      icon: github
    - link: https://twitter.com/michelvocks
      icon: twitter
    bulmalogo: true
